# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vdq9_3BSSKDda7tluDOhlFb1uFAdQiy0
"""

#20 number game



import random
print("Welcome to Count to 20")
print("Rules are simple:\nYou will start from sum=0. And you can add 1 or 2 number to the sum by turns. Who gets to 20 first wins!\nSimple and easy! Have fun!")
print("Select Mode: ")
a=int(input("Enter '1' for PvP and '2' for vs Computer\n "))

sum=[0]
victory=False
def game(add,player,sum):
    selected=[]
    if add==2:
        selected.append(str(sum[0]+1))
    sum[0]+=add
    selected.append(str(sum[0]))
    print(f'Selected numbers: {",".join(selected)}')

    if sum[0]>=20:
        print(f"{player} wins")
        return True
    return False
def get_number():
    x=int(input("How much you wanna add: "))
    if x not in [1,2]:
        print("Please select 1 or 2")
        x=get_number()
    return x
    
while victory==False:
        print("Player 1")
        num=get_number()
        victory=game(num,"Player 1",sum)
        if victory==True:
            break
        print("Player 2")
        if a==2:
            num=random.randint(1,2)
        else:
            num=get_number()
        victory=game(num,"Player 2",sum)